const removebytag = ["allthemodium:teleport_pad"];

ServerEvents.recipes((event) => {
  removebytag.forEach((item) => {
    event.remove({ id: item });
  });
});

const item_remove = [
  "allthemodium:alloy_paxel",
  "allthemodium:alloy_shovel",
  "allthemodium:alloy_pick",
  "allthemodium:alloy_axe",
  "allthemodium:alloy_sword",
  "allthemodium:alloy_trident",
  "allthemodium:vibranium_shield",
  "allthemodium:allthemodium_bow",
  "allthemodium:unobtainium_crossbow",
  "allthemodium:molten_allthemodium_bucket",
  "allthemodium:molten_vibranium_bucket",
  "allthemodium:molten_unobtainium_bucket",
  "allthemodium:vibranium_allthemodium_alloy_block",
  "allthemodium:unobtainium_vibranium_alloy_block",
  "allthemodium:unobtainium_allthemodium_alloy_block",
  "allthemodium:vibranium_allthemodium_alloy_ingot",
  "allthemodium:unobtainium_vibranium_alloy_ingot",
  "allthemodium:unobtainium_allthemodium_alloy_ingot",
  "allthemodium:vibranium_allthemodium_alloy_dust",
  "allthemodium:unobtainium_vibranium_alloy_dust",
  "allthemodium:unobtainium_allthemodium_alloy_dust",
  "immersiveengineering:ingot_electrum",
  "allthemodium:vibranium_gear",
  "allthemodium:allthemodium_gear",
  "allthemodium:unobtainium_plate",
  "allthemodium:vibranium_plate",
  "allthemodium:allthemodium_plate",
  "allthemodium:unobtainium_ingot",
  "allthemodium:vibranium_ingot",
  "allthemodium:allthemodium_ingot",
  "allthemodium:raw_unobtainium",
  "allthemodium:allthemodium_apple",
  "allthemodium:allthemodium_carrot",
  "allthemodium:allthemodium_helmet",
  "allthemodium:allthemodium_chestplate",
  "allthemodium:allthemodium_leggings",
  "allthemodium:allthemodium_boots",
  "allthemodium:vibranium_helmet",
  "allthemodium:vibranium_chestplate",
  "allthemodium:vibranium_leggings",
  "allthemodium:allthemodium_ore",
  "allthemodium:raw_unobtainium_block",
  "allthemodium:raw_vibranium_block",
  "allthemodium:raw_allthemodium_block",
  "allthemodium:unobtainium_boots",
  "allthemodium:unobtainium_leggings",
  "allthemodium:unobtainium_chestplate",
  "allthemodium:unobtainium_helmet",
  "allthemodium:vibranium_boots",
  "allthemodium:allthemodium_slate_ore",
  "allthemodium:vibranium_ore",
  "allthemodium:other_vibranium_ore",
  "allthemodium:unobtainium_ore",
  "allthemodium:allthemodium_block",
  "allthemodium:vibranium_block",
  "allthemodium:unobtainium_block",
  "allthemodium:raw_allthemodium",
  "allthemodium:raw_vibranium",
  "allthemodium:unobtainium_gear",
  "allthemodium:allthemodium_rod",
  "allthemodium:vibranium_rod",
  "allthemodium:unobtainium_rod",
  "allthemodium:allthemodium_nugget",
  "allthemodium:vibranium_nugget",
  "allthemodium:unobtainium_nugget",
  "allthemodium:allthemodium_dust",
  "allthemodium:vibranium_dust",
  "allthemodium:vibranium_pickaxe",
  "allthemodium:allthemodium_pickaxe",
  "allthemodium:vibranium_sword",
  "allthemodium:allthemodium_sword",
  "allthemodium:unobtainium_upgrade_smithing_template",
  "allthemodium:vibranium_upgrade_smithing_template",
  "allthemodium:allthemodium_upgrade_smithing_template",
  "allthemodium:unobtainium_dust",
  "allthemodium:unobtainium_mace",
  "allthemodium:allthemodium_axe",
  "allthemodium:vibranium_axe",
  "allthemodium:vibranium_mace",
  "allthemodium:allthemodium_shovel",
  "allthemodium:vibranium_shovel",
  "allthemodium:allthemodium_mace",
  "allthemodium:allthemodium_hoe",
  "allthemodium:vibranium_hoe",
];

ServerEvents.recipes((event) => {
  item_remove.forEach((item) => {
    event.remove({ output: item });
  });
});
